spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tracking
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Batch-Execution

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always